spring:
  #  profiles:
  #    active: dev
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:25433/${DB_NAME:avengers_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    show-sql: true

# Environment variables must be set in advance and not in this file for security reasons
# It is defined here for testing purposes